name: 215a
channels:
  - defaults
dependencies:
  - python
  - pip:
    - numpy==2.5.2
    - pandas==3.0.5
    - geopandas==1.2.0
    - matplotlib==3.11.1
    - seaborn==0.13.2
    - scikit-learn==1.9.0
    - scipy==1.18.1
    - jupyterlab==4.6.3
    - pyreadr==0.5.7
    - plotly==7.1.0
    - kaleido==1.4.0